name: Validate SemVer on Push

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to validate'
        required: false
        default: '1.0.0'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate SemVer string
        uses: ShubhamYadav25/validate-semver@v1.0.0
        with:
          version: ${{ github.event.inputs.version || '1.0.0' }}